runtime: python39
entrypoint: gunicorn -b :$PORT main:app  # Replace 'event_management' with your Django project folder name

# Handlers for static files and dynamic requests
handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

# Environment variables
env_variables:
  #DJANGO_SETTINGS_MODULE: "event_management.settings" 
 

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5


